Performance
ShaheerCH/Vet_clinic pull request #1
Opened 2022-08-31 08:20 UTC by ShaheerCH

2022-08-31 19:37 UTC, ShaheerCH commented
![01](https://user-images.githubusercontent.com/59507815/187767316-84e2ac39-7389-444a-9767-c91e97110f8c.png)

2022-08-31 19:37 UTC, ShaheerCH commented
![02](https://user-images.githubusercontent.com/59507815/187767353-3bdd90ef-605c-4543-8af4-c349efa82f27.png)

2022-08-31 19:40 UTC, ShaheerCH commented
![Uploading 03.png…]()

2022-08-31 19:41 UTC, ShaheerCH commented
![03](https://user-images.githubusercontent.com/59507815/187767966-471cc189-d569-463f-b777-2a366b98f250.png)

2022-08-31 20:05 UTC, Davidosky007 requested changes
Hi @ShaheerCH @Abel-desu 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* Well written PR description 👍 
* Descriptive commit messages 👍 
* Good looking readme file 👍 

## Required Changes ♻️
* Kindly add all the screenshots with `EXPLAIN ANALYZE` results ( before and after ) since they are 3 problematic queries you should have 6 screenshots 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 20:05 UTC, Davidosky007 commented on queries.sql
> +CREATE INDEX email_asc ON owners (email ASC);
* Kindly move all queries that modify your database( create tables and columns)  to the `schema.sql file ` as it is best practice

2022-09-01 09:53 UTC, ShaheerCH commented
![1](https://user-images.githubusercontent.com/59507815/187886421-19fd6819-5a63-45df-93a2-0ddb01b02d67.jpg)

2022-09-01 09:53 UTC, ShaheerCH commented
![2](https://user-images.githubusercontent.com/59507815/187886446-e3a1ea41-8d64-4156-baac-964c8bb6ced4.jpg)

2022-09-01 09:56 UTC, ShaheerCH commented
![3](https://user-images.githubusercontent.com/59507815/187886991-f52c9bbf-6ea0-4bb7-a2a2-1de833d0b2b4.png)

2022-09-01 10:18 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @ShaheerCH 🤝

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

- [ ] The execution time in the screenshots`before` is not significantly lower than 1 sec. You might need to run this query multiple times.

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-01 10:26 UTC, merged